name: advise--fabu
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '15 5,23 * * *'

jobs:
  release-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      ___X_CMD_GHACTION_X: x2
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: l
      git_email: l@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            x ws advise--fabu || true
            x:info "___X_CMD_ROOT_LOG: $___X_CMD_ROOT_LOG"
            x:info "GITHUB_ENV: $GITHUB_ENV"
            echo "___X_CMD_ROOT_LOG=$___X_CMD_ROOT_LOG" >> $GITHUB_ENV
          artifact_name: log
          artifact_path: ${{ env.___X_CMD_ROOT_LOG }}

