name: test x6 x7
on:
  workflow_dispatch:
    inputs:
      test-yy-version:
        description: 'test yy version'
        required: false
      XY_TEST_LOCAL_RUN:
        description: 'Whether to test in the current environment'
        required: false
  schedule:
    - cron: '40 11 * * *'

jobs:
  release-worker:
    runs-on: self-hosted

    timeout-minutes: 60
    env:
      # ___X_CMD_GHACTION_X: x2
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: l
      git_email: l@x-cmd.com
      gh_action_next: ""
      CONCURRENCY: 10
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TEST_REPORT_TOKEN: ${{ secrets.TEST_REPORT_TOKEN }}
      TEST_QYWX_WEBHOOK: ${{ secrets.TEST_QYWX_WEBHOOK }}
      test_yy_version: ${{ github.event.inputs.test-yy-version }}
      XY_TEST_LOCAL_RUN: ${{ github.event.inputs.XY_TEST_LOCAL_RUN }}
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            x ws fabu-test || true
            x:info "___X_CMD_ROOT_LOG: $___X_CMD_ROOT_LOG"
          artifact_name: log-test
          artifact_path: ~/.x-cmd.root/local/log
