name: x-bash => yy ( Excluding 2 7 )
on:
  workflow_dispatch:
    inputs:
      version-num:
        description: 'version number'
        required: false
      update-mod-list:
        description: 'update mod list'
        required: false
  schedule:
    - cron: '0 4,10,16,22 * * *'

jobs:
  release-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      ___X_CMD_GHACTION_X: x2
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: l
      git_email: l@x-cmd.com
      CONCURRENCY: 10
      gh_action_next: fabu-xx
      INPUTS_VERSION_NUM: ${{ github.event.inputs.version-num }}
      INPUTS_UPDATE_MOD_LIST: ${{ github.event.inputs.update-mod-list }}
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            x ws fabu-yy || true
            x:info "___X_CMD_ROOT_LOG: $___X_CMD_ROOT_LOG"
          artifact_name: log-yy
          artifact_path: ~/.x-cmd.root/local/log
