name: x-bash ==> yy
on:
  workflow_dispatch:
  schedule:
  - cron: '0 4,10,16,22 * * *'

jobs:
  release-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      ___X_CMD_GHACTION_X: x2
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: l
      git_email: l@x-cmd.com
      CONCURRENCY: 10
      gh_action_next: fabu-xx
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            x ws fabu-yy || true
            x:info "___X_CMD_ROOT_LOG: $___X_CMD_ROOT_LOG"
          artifact_name: log
          artifact_path: ~/.x-cmd.root/local/log/r/DEFAULT
