name: x-bash => y7 => x7
on:
  workflow_dispatch:
    inputs:
      update-mod-list:
        description: 'update mod list'
        required: false
  # schedule:
  # - cron: '10 22 * * *'

jobs:
  release-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      ___X_CMD_GHACTION_X: x2
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: l
      git_email: l@x-cmd.com
      gh_action_next: ""
      CONCURRENCY: 10
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INPUTS_UPDATE_MOD_LIST: ${{ github.event.inputs.update-mod-list }}
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            x ws fabu-yy 7 || true
            x ws fabu-xx 7 || true
            x:info "___X_CMD_ROOT_LOG: $___X_CMD_ROOT_LOG"
          artifact_name: log-yx7
          artifact_path: ~/.x-cmd.root/local/log
