name: yy => xx (excluding x2 x7)
on:
  workflow_dispatch:
    inputs:
      version-num:
        description: 'version number'
        required: false
      prepare-extmeta-version:
        description: 'prepare extmeta version'
        required: false
  schedule:
    - cron: '20 4,10,16,22 * * *'

jobs:
  release-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      ___X_CMD_GHACTION_X: x2
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: l
      git_email: l@x-cmd.com
      gh_action_next: ""
      CONCURRENCY: 10
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INPUTS_VERSION_NUM: ${{ github.event.inputs.version-num }}
      INPUTS_PREPARE_EXTMETA_VERSION: ${{ github.event.inputs.prepare-extmeta-version }}
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            x ws fabu-xx || true
            x:info "___X_CMD_ROOT_LOG: $___X_CMD_ROOT_LOG"
          artifact_name: log-xx
          artifact_path: ~/.x-cmd.root/local/log
