name: oss sync scp
on:
  workflow_dispatch:
    inputs:
      sync-item:
        description: 'sync item'
        required: false
  # schedule:
    # - cron: '10 4,10,16,22 * * *'

jobs:
  release-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      ___X_CMD_GHACTION_X: x2
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OSS_SSH_PRIVATE_KEY: ${{ secrets.OSS_QIAKAI_SSH_PRIVATE_KEY }}
      QYWX_BOT_RELEASE_WEBHOOK: ${{ secrets.QYWX_BOT_RELEASE_WEBHOOK }}
      GITHUB_SYNC: ${{ github.event.inputs.sync-item }}
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            x ws oss-sync-scp
