name: Generate xx-release
on:
  push:
  workflow_dispatch:

jobs:
  release-worker:
    runs-on: ubuntu-latest
    env:
      ___X_CMD_GHACTION_X: x0
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: l
      git_email: l@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action
        with:
          code: x ws xx-release || true
